language: R
sudo: false
cache: packages
pandoc_version: 1.19.2.1
r_github_packages:
  - jimhester/covr

before_install:
  - tlmgr install tex-gyre fontaxes

repos:
  CRAN: https://cran.rstudio.com/

after_success:
  - Rscript -e 'covr::codecov()'

r:
  - oldrel
  - release
  - devel
