language: R
sudo: false
cache: packages
pandoc_version: 1.19.2.1
r_github_packages:
  - jimhester/covr



repos:
  CRAN: https://cran.rstudio.com/

matrix:
  include:
    - r: devel
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes'

    - r: release
      r_build_args: --compact-vignettes=both
      before_install:
        - tlmgr install fontaxes sttools mweights libertine mathalfa
      after_success:
        - Rscript -e 'covr::codecov()'

    - r: oldrel
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes'

    - os: osx
      r: release
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

    - os: osx
      r: oldrel
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

